---
- name: include_tasks system_tuning.yml
  include_tasks: system_tuning.yml

- name: install dependencies
  package:
    name: parted
    state: present
  register: result
  until: result is succeeded
  when:
    - not containerized_deployment
    - ansible_os_family != 'ClearLinux'

- name: include_tasks common.yml
  include_tasks: common.yml

- name: include build_devices.yml
  include: build_devices.yml

- name: read information about the devices
  parted:
    device: "{{ item }}"
    unit: MiB
  register: parted_results
  with_items: "{{ devices }}"

- name: include check_gpt.yml
  include_tasks: check_gpt.yml
  when:
    - osd_scenario != 'lvm'

- name: include check_gpt.yml
  include: check_gpt.yml
  when:
    - osd_scenario != 'lvm'

- name: include scenarios/collocated.yml
  include: scenarios/collocated.yml
  when:
    - osd_scenario == 'collocated'

- name: include_tasks scenarios/non-collocated.yml
  include_tasks: scenarios/non-collocated.yml
  when:
    - not osd_auto_discovery
    - osd_scenario == 'non-collocated'

- name: include_tasks scenarios/lvm.yml
  include_tasks: scenarios/lvm.yml
  when:
    - osd_scenario == 'lvm'
    - lvm_volumes|length > 0
  # Hard code this so we will skip the entire file instead of individual tasks (Default isn't Consistent)
  static: False

- name: include_tasks scenarios/lvm-batch.yml
  include_tasks: scenarios/lvm-batch.yml
  when:
    - not containerized_deployment
    - osd_scenario != 'lvm'
  # Hard code this so we will skip the entire file instead of individual tasks (Default isn't Consistent)
  static: False

- name: include_tasks activate_osds.yml
  include_tasks: activate_osds.yml
  when:
    - not containerized_deployment
    - osd_scenario != 'lvm'
  # Hard code this so we will skip the entire file instead of individual tasks (Default isn't Consistent)
  static: False

- name: set_fact keys - override keys_tmp with keys
  set_fact:
    openstack_keys: "{{ openstack_keys_tmp }}"
  when:
    - not add_osd|default(False)
    - openstack_keys_tmp is defined

# Create the pools listed in openstack_pools
- name: include openstack_config.yml
  include_tasks: openstack_config.yml
  when:
    - not add_osd|default(False)
    - openstack_config
    - inventory_hostname == groups[osd_group_name] | last
