---
- include: check_mandatory_vars.yml

- include: pre_requisite.yml
  when: not osd_containerized_deployment
  # Hard code this so we will skip the entire file instead of individual tasks (Default isn't Consistent)
  static: False

- include: create_devices_list.yml
  # FG: Always execute: map devices_static to devices, or create devices from devices_multipath_regex when devices_multipath_auto
  static: False

- include: ./scenarios/journal_collocation.yml
  when:
    - journal_collocation
    - not osd_containerized_deployment
  # Hard code this so we will skip the entire file instead of individual tasks (Default isn't Consistent)
  static: False

- include: ./scenarios/raw_multi_journal.yml
  when:
    - raw_multi_journal
    - not osd_containerized_deployment
  # Hard code this so we will skip the entire file instead of individual tasks (Default isn't Consistent)
  static: False

- include: ./scenarios/bluestore.yml
  when:
    - osd_objectstore == 'bluestore'
    - not osd_containerized_deployment
  # Hard code this so we will skip the entire file instead of individual tasks (Default isn't Consistent)
  static: False

- include: ./scenarios/dmcrypt-journal-collocation.yml
  when:
    - dmcrypt_journal_collocation
    - not osd_containerized_deployment
  # Hard code this so we will skip the entire file instead of individual tasks (Default isn't Consistent)
  static: False

- include: ./scenarios/dmcrypt-dedicated-journal.yml
  when:
    - dmcrypt_dedicated_journal
    - not osd_containerized_deployment
  # Hard code this so we will skip the entire file instead of individual tasks (Default isn't Consistent)
  static: False

- include: ./docker/main.yml
  when: osd_containerized_deployment
  # Hard code this so we will skip the entire file instead of individual tasks (Default isn't Consistent)
  static: False
