---
# 

- name: check whether multipath is being used
  command: multipathd show
  changed_when: false
  failed_when: false
  register: has_multipath
- name: gather whitelisted devices
  shell: multipathd list devices | grep whitelisted | awk '{print $1}'
  changed_when: false
  failed_when: false
  register: devices_multipath_skip
  when: "has_multipath.rc == 0"
- name: gather multipaths, skip first line
  shell: multipathd list multipaths | awk 'BEGIN{i=0}{if (i == 0 ) {i++} else {print $1}}'
  changed_when: false
  failed_when: false
  register: devices_multipaths
  when: "has_multipath.rc == 0"

- debug: "msg='has_multipath is {{ has_multipath.rc }}'"
- debug: "msg='devices_multipath_skip is {{ devices_multipath_skip }}'"
- debug: "msg='devices_multipaths is {{ devices_multipaths }}'"

- name:	check multipaths matching regex
  shell: echo /dev/mapper/{{ item }}
  with_items: 
  - "{{ devices_multipaths.stdout_lines }}"
  changed_when: false
  failed_when: false
  register: devices_multipath_results
  when:
   - "has_multipath.rc == 0"
   - item.find('{{ devices_multipath_regex }}') == 0
   - dedicated_devices is not defined or (dedicated_devices is defined and not ((dedicated_devices | join(" ")) | search('{{ item }}')))

- name: get list of selected multipaths
  set_fact: devices_multipath_list="{{ devices_multipath_results.results | map(attribute='stdout') | select("defined") | list }}"
  when:
   - "has_multipath.rc == 0"

#FG# - debug: var=devices_multipath_list

- name: combine devices
  set_fact:
    devices: "{{ devices_multipath_list }}"

- debug: var=devices

#FG#
- name: set useful variable logfile_path
  set_fact:
    logfile_path: "{{ playbook_dir }}/../lv-create.log"
- name: check if file containing list of LVM volumes exists
  stat: 
    path: "{{ logfile_path }}_{{ ansible_hostname }}"
  delegate_to: localhost
  register: lvm_volumes_file
- name: Include file with lvm_volumes definitions
  include_vars: "{{ logfile_path }}_{{ ansible_hostname }}"
  delegate_to: localhost
  when: lvm_volumes_file.stat.exists == True
